backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "CV"
    label: "Profile"
    files:
      - file: "src/pages/profile.md"
        label: "Profile"
        name: "profile"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: profile}
          - {label: Name, name: name, widget: string}
          - {label: Phone, name: phone, widget: string}
          - {label: Email, name: email, widget: string}
          - {label: Github, name: github, widget: string}
          - {label: Linkedin, name: linkedin, widget: string}
          - {label: Linkedin Image, name: linkedinImage, widget: string}
          - {label: Description, name: description, widget: text}
          - {label: Summary, name: summary, widget: text}
          - {label: Interests, name: interests, widget: text}
          - { label: Experience,
              name: experience,
              widget: list,
              fields:
              [
                {label: Company, name: company, widget: string},
                {label: Title, name: title, widget: string},
                {label: Description, name: description, widget: text, required: false},
                {label: Technologies, name: technologies, widget: text, required: false},
                {label: Date From, name: dateFrom, widget: date, format: 'MMMM YYYY'},
                {label: Date To, name: dateTo, widget: date, format: 'MMMM YYYY', required: false },
                {label: Location, name: location, widget: string},
              ]
            }
          - { label: Education,
              name: education,
              widget: list,
              fields:
              [
                {label: Institution, name: institution, widget: string},
                {label: Title, name: title, widget: string},
                {label: Date To, name: dateTo, widget: date, format: 'YYYY'},
              ]
            }
          - {label: Skills,
              name: skills,
              required: true,
              widget: list,
              fields:
              [
                { label: Skill, name: skill, required: true, widget: string },
                {
                  label: Rating,
                  name: rating,
                  required: false,
                  widget: "number",
                  default: 10,
                  valueType: "int",
                  min: 1,
                  max: 10,
                  step: 1,
                }
              ]
            }
